-- Create the cash_register_status table
CREATE TABLE IF NOT EXISTS cash_register_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable Row Level Security (RLS)
ALTER TABLE cash_register_status ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows all operations
CREATE POLICY "Allow all operations for authenticated users"
    ON cash_register_status
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);